server:
  port: 8081

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:Mapping/*Mapper.xml

#showSql
logging:
  level:
    com:
      example:
        mapper : debug